# Generated by Django 3.2.9 on 2021-11-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('description', models.TextField(max_length=5000, verbose_name='Description')),
                ('series', models.PositiveIntegerField(default=0, verbose_name='Series')),
                ('type', models.CharField(choices=[('TV', 'TV Series'), ('OVA', 'OVA'), ('FILM', 'FILM')], max_length=30)),
                ('date_aired', models.DateTimeField(verbose_name='Airing started')),
                ('date_aired_end', models.DateTimeField(verbose_name='Airing ended')),
                ('status', models.CharField(choices=[('Airing', 'Airing'), ('Ended', 'Ended')], max_length=50, verbose_name='Status')),
                ('rating', models.IntegerField(choices=[(1, 'Insignificantly'), (2, 'Ugly'), (3, 'Bad'), (4, 'Anyhow'), (5, 'Mediocre'), (6, 'Not bad'), (7, 'Good'), (8, 'Great'), (9, 'Superb'), (10, 'Masterpiece')])),
                ('views', models.PositiveIntegerField(default=0)),
                ('trending', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('image', models.ImageField(default='f', upload_to='anime/images', verbose_name='Image')),
                ('slug', models.SlugField(default='dummy-anime', verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'ordering': ['title', '-rating'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('description', models.TextField(max_length=5000)),
                ('slug', models.SlugField(default='dummy-slug', verbose_name='Slug')),
                ('image', models.ImageField(default='f', upload_to='genre/images')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['-title'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Studio',
                'verbose_name_plural': 'Studios',
                'ordering': ['-name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.ImageField(upload_to='', verbose_name='Banner Image')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='categories',
            field=models.ManyToManyField(to='api.Genre', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studio'),
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('genre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.genre')),
                ('genre_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_genre', to='api.genre')),
            ],
            options={
                'verbose_name': 'Sub Genre',
                'verbose_name_plural': 'Sub Genres',
                'ordering': ['-title'],
                'managed': True,
            },
            bases=('api.genre',),
        ),
    ]
