# Generated by Django 3.2.9 on 2021-12-05 11:55

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(default='f', upload_to=api.helpers.PathAndRename('images/animes'), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(upload_to=api.helpers.PathAndRename('images/banners'), verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='f', upload_to=api.helpers.PathAndRename('images/genres')),
        ),
        migrations.RemoveField(
            model_name='subgenre',
            name='genre_of',
        ),
        migrations.AddField(
            model_name='subgenre',
            name='genre_of',
            field=models.ManyToManyField(related_name='sub_genre', to='api.Genre'),
        ),
    ]
