# Generated by Django 3.2.9 on 2021-12-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211205_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubGenre',
        ),
    ]
