# Generated by Django 3.2.9 on 2021-12-06 21:59

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_subgenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('description', models.TextField(max_length=5000)),
                ('slug', models.SlugField(default='dummy-slug', verbose_name='Slug')),
                ('image', models.ImageField(default='f', upload_to=api.helpers.PathAndRename('images/genres'))),
                ('genre_of', models.ManyToManyField(related_name='sub_genre', to='api.Genre')),
            ],
            options={
                'verbose_name': 'Sub Genre',
                'verbose_name_plural': 'Sub Genres',
                'ordering': ['-title'],
                'managed': True,
            },
        ),
    ]
